### PR TITLE
removed leading http from fonts ref link

### PR DESCRIPTION
**Pull request by TinaHeiligers**
Hey there,
I love your theme but struggled to get it working if hosting on github.
With some help, I figured out the cause was github insisting on using https. Once this is removed from the base.html fonts references, it all works great.
Thanks for the theme!
Tina

### CODE REVIEW

**Comment by porterjamesj** [comment]
Oh wow, sorry about that, and thank you for the contribution! If you wouldn't mind removing the CSS changes, I'll go ahead and merge.

**Comment by TinaHeiligers** [comment]
Oops!,
I didn't mean to be working on it in this repo.

**Comment by TinaHeiligers** [comment]
I think i removed the css changes.
Sorry about messing around on this repo, I was trying to work on my forked version.

**Comment by porterjamesj** [comment]
thank you!

**Comment by TinaHeiligers** [comment]
Glad to be contributing.
Tina

**Pull request merged**
